### ISSUE TITLE
Assignment 2 plans

### ISSUE THREAD

**Issue by Thanh-8213** [etc5521-2020/assignment-1-hakea#4]
Hello, 
This is our assignment 2 plan
 

- New question:

1. Compare the types of bean (Arabica and Robusta)
2. Reasearch more on Fair Trade

- Improvement of current reports:
1. Boxplot instead of Pie chart for question 1
2. Using grid arrange to tidy the radar charts.
3. Leading region, changing the measure from SUM to MEAN.
4. Remove individual criteria/ Overall quality regression (Variables are correlated)

**Comment by rlin0004** [comment]
Details on Fairtrade coffee:
The primary question for the report "All about coffee" is summarized as "Why are the best-graded coffee beans considered the best?", I have taken the fair trade coffee as a sub-element into consideration to broadening the scope of the report. Therefore, the possible new secondary question here is:
**"Whether a top-graded coffee bean producers are certified as having been produced to fair trade standards."** 

Since this secondary question option is more about research, which I'm not sure if it is suitable for the assignment, I have provided a backup secondary question.
**"Are there any similarities in the processing method of coffee beans amongst the best-graded coffee beans countries?"**

In addition to the improvements:
We will also rephrase the motivation & intro.

**Comment by Thanh-8213** [comment]
2020/09/13 update:
Compare the types of bean (Arabica and Robusta) is not available (Only 28 Robusta). I will come up with another question.

**Comment by dicook** [comment]
Dang and Rui,

This outline for mapping out the revisions is very minimal, and makes it difficult to see how you plan to go about improving on the original report. You should 

- map the inadequacies for the first report into changes required to fix, 
- re-visit the data description and explain how the changes will help to better understand the data problem, and answer the question. how will the new questions expand the understanding, for example.
- list what will be important to include in the conclusions
